### ISSUE TITLE
Crash when loading with Eldritch Mobs

### ISSUE THREAD

**Issue by OarisHunter** [Jamalam360/ExcessEnchantments#5]
Game crashes whenever eldritch mobs is also installed.
https://www.curseforge.com/minecraft/mc-mods/eldritch-mobs

`[22:52:42] [main/FATAL]: Mixin apply failed excessenchantmentsfabric.mixins.json:LivingEntityMixin -> net.minecraft.class_1309: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE overwrite method teleportRandomly in excessenchantmentsfabric.mixins.json:LivingEntityMixin cannot reduce visibiliy of PROTECTED target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE overwrite method teleportRandomly in excessenchantmentsfabric.mixins.json:LivingEntityMixin cannot reduce visibiliy of PROTECTED target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:466) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethod(MixinPreProcessorStandard.java:577) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:267) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:425) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]`

**Comment by Jamalam360** [comment]
Sorry to hear you've been having this issue, I should be able to fix it and release the fix in a new version today

**Comment by Jamalam360** [comment]
ok, this is fixed in the latest release that will be available on curseforge soon
